### PR TITLE
updates for fcsl-pcm 1.3

### LINKED ISSUE #11: Update for fcsl-pcm 1.3
The upcoming version of fcsl-pcm breaks the build.

### PR DESCRIPTION
**Pull request by clayrat**
Closes #11

### CODE REVIEW

**Comment by clayrat** [comment]
Build fails because https://github.com/coq/opam-coq-archive/pull/1450 is still not merged.

**Comment by palmskog** [comment]
@clayrat can you please adjust the opam bound for `coq-fcsl-pcm` so that we can test the `dev` version of FCSL PCM in CI? Same as for MathComp and Coq.

**Comment by clayrat** [comment]
> @clayrat can you please adjust the opam bound for `coq-fcsl-pcm` so that we can test the `dev` version of FCSL PCM in CI? Same as for MathComp and Coq.

Which one is that?

**Comment by clayrat** [comment]
Oh, you mean adding the `| (= "dev")` part?

**Comment by palmskog** [comment]
> Oh, you mean adding the `| (= "dev")` part?

This is only one of many ways to allow `dev` versions, but yes, you can add that one.

**Comment by palmskog** [comment]
@clayrat CI fails with parsing error for an opam file:
```
At /home/coq/.opam/4.05.0/.opam-switch/sources/coq-disel/coq-disel.opam:26:18: Parse error
```
You can use `opam lint coq-disel.opam` and similar to check an opam file locally for problems.

**Comment by clayrat** [comment]
Oh, the build is failing for 8.10 because we don't support it in FCSL-PCM anymore. I guess I'll drop it for Disel too, or is it really required?

**Comment by palmskog** [comment]
@clayrat would be nice if you could adjust the Coq opam bound to greater than 8.10 for Disel too.

**Pull request merged**
